#ifndef LOC_TYPES_H
#define LOC_TYPES_H

#include <string>
#include <array>
#include "defines.h"

#define LOC_TEXT_SYMBOL_SIZE 3
#define LOC_TEXT_VARIABLE_SIZE 12

typedef enum loc_text_id {
  LOC_TEXT_UNDEFINED,

  LOC_TEXT_MAINMENU_BUTTON_TEXT_PLAY,
  LOC_TEXT_MAINMENU_BUTTON_TEXT_CHARACTER,
  LOC_TEXT_MAINMENU_BUTTON_TEXT_SETTINGS,
  LOC_TEXT_MAINMENU_BUTTON_TEXT_EXIT,
  LOC_TEXT_MAINMENU_BUTTON_TEXT_EDITOR,
  
  LOC_TEXT_MMS_CHARACTER_BUTTON_ENTER_TAB_UPGRADE,
  LOC_TEXT_MMS_CHARACTER_UPGRADE_SUBSCENE_UPGRADE_BTN,
  LOC_TEXT_MMS_CHARACTER_BUTTON_ENTER_TAB_INVENTORY,
  LOC_TEXT_MMS_CHARACTER_BUTTON_ENTER_TAB_STATS,
  LOC_TEXT_MMS_CHARACTER_BUTTON_BACK,
  LOC_TEXT_MMS_CHARACTER_TAB_STATS_BUTTON_UPGRADE,
  LOC_TEXT_MMS_CHARACTER_TAB_STATS_CURRENCY_TEXT_TOTAL,
  LOC_TEXT_MAINMENU_PAUSE_BUTTON_TEXT_RESUME,
  LOC_TEXT_MAINMENU_PAUSE_BUTTON_TEXT_EXIT_TO_MAINMENU,
  LOC_TEXT_MAINMENU_PAUSE_BUTTON_TEXT_EXIT_TO_DESKTOP,
  LOC_TEXT_MAINMENU_MAP_CHOICE_BACK,
  LOC_TEXT_MAINMENU_TRAIT_CHOICE_AVAILABLE_TRAITS_TITLE,
  LOC_TEXT_MAINMENU_TRAIT_CHOICE_CHOSEN_TRAITS_TITLE,
  LOC_TEXT_MAINMENU_TRAIT_ABILITY_CHOICE_PANEL_TITLE,
  LOC_TEXT_MAINMENU_TRAIT_CHOICE_BUTTON_BACK,
  LOC_TEXT_MAINMENU_TRAIT_CHOICE_BUTTON_ACCEPT,
  LOC_TEXT_MAINMENU_TRAIT_CHOICE_PANEL_REMANING_TRAIT_POINTS,

  LOC_TEXT_SETTINGS_SDR_WINDOW_MODE_WINDOWED,
  LOC_TEXT_SETTINGS_SDR_WINDOW_MODE_BORDERLESS,
  LOC_TEXT_SETTINGS_SDR_WINDOW_MODE_FULLSCREEN,
  LOC_TEXT_SETTINGS_BUTTON_APPLY,
  LOC_TEXT_SETTINGS_BUTTON_CANCEL,
  LOC_TEXT_SETTINGS_BUTTON_ENGLISH,
  LOC_TEXT_SETTINGS_BUTTON_TURKISH,

  LOC_TEXT_EDITOR_SDR_PROP_CHANGE_TREE,
  LOC_TEXT_EDITOR_SDR_PROP_CHANGE_TOMBSTONE,
  LOC_TEXT_EDITOR_SDR_PROP_CHANGE_STONE,
  LOC_TEXT_EDITOR_SDR_PROP_CHANGE_SPIKE,
  LOC_TEXT_EDITOR_SDR_PROP_CHANGE_SKULL,
  LOC_TEXT_EDITOR_SDR_PROP_CHANGE_PILLAR,
  LOC_TEXT_EDITOR_SDR_PROP_CHANGE_LAMP,
  LOC_TEXT_EDITOR_SDR_PROP_CHANGE_FENCE,
  LOC_TEXT_EDITOR_SDR_PROP_CHANGE_DETAIL,
  LOC_TEXT_EDITOR_SDR_PROP_CHANGE_CANDLE,
  LOC_TEXT_EDITOR_SDR_PROP_CHANGE_BUILDING,
  LOC_TEXT_EDITOR_SDR_PROP_CHANGE_SPRITE,

  LOC_TEXT_INGAME_LABEL_PRESS_SPACE,
  LOC_TEXT_INGAME_UPGRADE_ABILITY_NEW,
  LOC_TEXT_INGAME_UPGRADE_ABILITY_DAMAGE,
  LOC_TEXT_INGAME_UPGRADE_ABILITY_AMOUTH,
  LOC_TEXT_INGAME_UPGRADE_ABILITY_HITBOX,
  LOC_TEXT_INGAME_UPGRADE_ABILITY_SPEED,
  LOC_TEXT_INGAME_STATE_RESULT_CLEARED,
  LOC_TEXT_INGAME_STATE_RESULT_DEAD,
  LOC_TEXT_INGAME_STATE_RESULT_COLLECTED_COINS,
  LOC_TEXT_INGAME_STATE_RESULT_ACCEPT,
  LOC_TEXT_INGAME_STATE_CHEST_OPENING_SPIN,
  LOC_TEXT_INGAME_GAME_RULE_SPAWN_MULTIPLIER,
  LOC_TEXT_INGAME_GAME_RULE_PLAY_TIME_MULTIPLIER,
  LOC_TEXT_INGAME_GAME_RULE_DELTA_TIME_MULTIPLIER,
  LOC_TEXT_INGAME_GAME_RULE_BOSS_MODIFIER,
  LOC_TEXT_INGAME_GAME_RULE_AREA_UNLOCKER,
  LOC_TEXT_INGAME_GAME_RULE_TRAIT_POINT_MODIFIER,
  LOC_TEXT_INGAME_GAME_RULE_BONUS_RESULT_MULTIPLIER,
  LOC_TEXT_INGAME_GAME_RULE_ZOMBIE_LEVEL_MODIFIER,
  LOC_TEXT_INGAME_GAME_RULE_RESERVED_FOR_FUTURE_USE,
  LOC_TEXT_INGAME_GAME_RULE_SPAWN_MULTIPLIER_DESCRIPTION,
  LOC_TEXT_INGAME_GAME_RULE_PLAY_TIME_MULTIPLIER_DESCRIPTION,
  LOC_TEXT_INGAME_GAME_RULE_DELTA_TIME_MULTIPLIER_DESCRIPTION,
  LOC_TEXT_INGAME_GAME_RULE_BOSS_MODIFIER_DESCRIPTION,
  LOC_TEXT_INGAME_GAME_RULE_AREA_UNLOCKER_DESCRIPTION,
  LOC_TEXT_INGAME_GAME_RULE_TRAIT_POINT_MODIFIER_DESCRIPTION,
  LOC_TEXT_INGAME_GAME_RULE_BONUS_RESULT_MULTIPLIER_DESCRIPTION,
  LOC_TEXT_INGAME_GAME_RULE_ZOMBIE_LEVEL_MODIFIER_DESCRIPTION,
  LOC_TEXT_INGAME_GAME_RULE_RESERVED_FOR_FUTURE_USE_DESCRIPTION,

  LOC_TEXT_PLAYER_STAT_LIFE_ESSENCE,
  LOC_TEXT_PLAYER_STAT_DESC_LIFE_ESSENCE,
  LOC_TEXT_PLAYER_STAT_BREAD,
  LOC_TEXT_PLAYER_STAT_DESC_BREAD,
  LOC_TEXT_PLAYER_STAT_CARDINAL_BOOTS,
  LOC_TEXT_PLAYER_STAT_DESC_CARDINAL_BOOTS,
  LOC_TEXT_PLAYER_STAT_BLAST_SCROLL,
  LOC_TEXT_PLAYER_STAT_DESC_BLAST_SCROLL,
  LOC_TEXT_PLAYER_STAT_HEAVY_CROSS,
  LOC_TEXT_PLAYER_STAT_DESC_HEAVY_CROSS,
  LOC_TEXT_PLAYER_STAT_HOURGLASS,
  LOC_TEXT_PLAYER_STAT_DESC_HOURGLASS,
  LOC_TEXT_PLAYER_STAT_SECOND_HAND,
  LOC_TEXT_PLAYER_STAT_DESC_SECOND_HAND,
  LOC_TEXT_PLAYER_STAT_SEEING_EYES,
  LOC_TEXT_PLAYER_STAT_DESC_SEEING_EYES,
  LOC_TEXT_PLAYER_STAT_TOTAL_TRAIT_POINTS,
  LOC_TEXT_PLAYER_STAT_DESC_TOTAL_TRAIT_POINTS,
  LOC_TEXT_PLAYER_ABILITY_NAME_BULLET,
  LOC_TEXT_PLAYER_ABILITY_NAME_ARCANE_CODEX,
  LOC_TEXT_PLAYER_ABILITY_NAME_COMET,
  LOC_TEXT_PLAYER_ABILITY_NAME_FIREBALL,
  LOC_TEXT_PLAYER_ABILITY_NAME_FIRETRAIL,
  LOC_TEXT_PLAYER_ABILITY_NAME_RADIENCE,

  LOC_TEXT_PLAYER_TRAIT_ALACRITY,
  LOC_TEXT_PLAYER_TRAIT_FORTITUDE,
  LOC_TEXT_PLAYER_TRAIT_POWER,
  LOC_TEXT_PLAYER_TRAIT_FORTUNE,
  LOC_TEXT_PLAYER_TRAIT_KEEN,
  LOC_TEXT_PLAYER_TRAIT_SERENDIPITY,
  LOC_TEXT_PLAYER_TRAIT_VIGOR,
  LOC_TEXT_PLAYER_TRAIT_PERSISTENCE,
  LOC_TEXT_PLAYER_TRAIT_AFFLICTION,
  LOC_TEXT_PLAYER_TRAIT_FRENZY,
  LOC_TEXT_PLAYER_TRAIT_BRUTALITY,
  LOC_TEXT_PLAYER_TRAIT_DEVASTATOR,
  LOC_TEXT_PLAYER_TRAIT_RESILIENCE,
  LOC_TEXT_PLAYER_TRAIT_AMPLITUDE,
  LOC_TEXT_PLAYER_TRAIT_EXPEDITION,
  LOC_TEXT_PLAYER_TRAIT_TRIBUTE,
  LOC_TEXT_PLAYER_TRAIT_STAGGER,
  LOC_TEXT_PLAYER_TRAIT_SIGILIC,
  LOC_TEXT_PLAYER_TRAIT_VITALITY_SYNERGY,
  LOC_TEXT_PLAYER_TRAIT_LETHAL_SYNERGY,

  LOC_TEXT_PLAYER_TRAIT_EXERTION,
  LOC_TEXT_PLAYER_TRAIT_HOBBLED,
  LOC_TEXT_PLAYER_TRAIT_MYOPIA,
  LOC_TEXT_PLAYER_TRAIT_HEMOPHILIA,
  LOC_TEXT_PLAYER_TRAIT_DREAD,
  LOC_TEXT_PLAYER_TRAIT_INFECTION,
  LOC_TEXT_PLAYER_TRAIT_CLUMSY,
  LOC_TEXT_PLAYER_TRAIT_BACKLASH,
  LOC_TEXT_PLAYER_TRAIT_OBSCURED_VITALS,
  LOC_TEXT_PLAYER_TRAIT_TUNNEL_VISION,
  LOC_TEXT_PLAYER_TRAIT_JITTERY,
  LOC_TEXT_PLAYER_TRAIT_FORGETFUL,
  LOC_TEXT_PLAYER_TRAIT_BLOOD_SCENT,
  LOC_TEXT_PLAYER_TRAIT_APATHY,
  LOC_TEXT_PLAYER_TRAIT_IGNORANCE,
  LOC_TEXT_PLAYER_TRAIT_BLUNTED,
  LOC_TEXT_PLAYER_TRAIT_ENCUMBERED,

  LOC_TEXT_PLAYER_TRAIT_ALACRITY_DESC,
  LOC_TEXT_PLAYER_TRAIT_FORTITUDE_DESC,
  LOC_TEXT_PLAYER_TRAIT_POWER_DESC,
  LOC_TEXT_PLAYER_TRAIT_FORTUNE_DESC,
  LOC_TEXT_PLAYER_TRAIT_KEEN_DESC,
  LOC_TEXT_PLAYER_TRAIT_SERENDIPITY_DESC,
  LOC_TEXT_PLAYER_TRAIT_VIGOR_DESC,
  LOC_TEXT_PLAYER_TRAIT_PERSISTENCE_DESC,
  LOC_TEXT_PLAYER_TRAIT_AFFLICTION_DESC,
  LOC_TEXT_PLAYER_TRAIT_FRENZY_DESC,
  LOC_TEXT_PLAYER_TRAIT_BRUTALITY_DESC,
  LOC_TEXT_PLAYER_TRAIT_DEVASTATOR_DESC,
  LOC_TEXT_PLAYER_TRAIT_RESILIENCE_DESC,
  LOC_TEXT_PLAYER_TRAIT_AMPLITUDE_DESC,
  LOC_TEXT_PLAYER_TRAIT_EXPEDITION_DESC,
  LOC_TEXT_PLAYER_TRAIT_TRIBUTE_DESC,
  LOC_TEXT_PLAYER_TRAIT_STAGGER_DESC,
  LOC_TEXT_PLAYER_TRAIT_SIGILIC_DESC,
  LOC_TEXT_PLAYER_TRAIT_VITALITY_SYNERGY_DESC,
  LOC_TEXT_PLAYER_TRAIT_LETHAL_SYNERGY_DESC,

  LOC_TEXT_PLAYER_TRAIT_EXERTION_DESC,
  LOC_TEXT_PLAYER_TRAIT_HOBBLED_DESC,
  LOC_TEXT_PLAYER_TRAIT_MYOPIA_DESC,
  LOC_TEXT_PLAYER_TRAIT_HEMOPHILIA_DESC,
  LOC_TEXT_PLAYER_TRAIT_DREAD_DESC,
  LOC_TEXT_PLAYER_TRAIT_INFECTION_DESC,
  LOC_TEXT_PLAYER_TRAIT_CLUMSY_DESC,
  LOC_TEXT_PLAYER_TRAIT_BACKLASH_DESC,
  LOC_TEXT_PLAYER_TRAIT_OBSCURED_VITALS_DESC,
  LOC_TEXT_PLAYER_TRAIT_TUNNEL_VISION_DESC,
  LOC_TEXT_PLAYER_TRAIT_JITTERY_DESC,
  LOC_TEXT_PLAYER_TRAIT_FORGETFUL_DESC,
  LOC_TEXT_PLAYER_TRAIT_BLOOD_SCENT_DESC,
  LOC_TEXT_PLAYER_TRAIT_APATHY_DESC,
  LOC_TEXT_PLAYER_TRAIT_IGNORANCE_DESC,
  LOC_TEXT_PLAYER_TRAIT_BLUNTED_DESC,
  LOC_TEXT_PLAYER_TRAIT_ENCUMBERED_DESC,

  LOC_TEXT_SIGIL_NAME_HEAD,
  LOC_TEXT_SIGIL_NAME_ARCH_MICHAEL,
  LOC_TEXT_SIGIL_NAME_ARCH_GABRIEL,
  LOC_TEXT_SIGIL_NAME_ARCH_RAPHAEL,
  LOC_TEXT_SIGIL_NAME_ARCH_URIEL,
  LOC_TEXT_SIGIL_NAME_ARCH_SAMAEL,
  LOC_TEXT_SIGIL_NAME_ARCH_ZADKIEL,
  LOC_TEXT_SIGIL_NAME_ARCH_THAVAEL,
  LOC_TEXT_SIGIL_NAME_ARCH_AZRAEL,
  LOC_TEXT_SIGIL_NAME_ARCH_CAMAEL,
  LOC_TEXT_SIGIL_NAME_ARCH_JOPHIEL,

  LOC_TEXT_SIGIL_DESC_ARCH_MICHAEL,
  LOC_TEXT_SIGIL_DESC_ARCH_GABRIEL,
  LOC_TEXT_SIGIL_DESC_ARCH_RAPHAEL,
  LOC_TEXT_SIGIL_DESC_ARCH_URIEL,
  LOC_TEXT_SIGIL_DESC_ARCH_SAMAEL,
  LOC_TEXT_SIGIL_DESC_ARCH_ZADKIEL,
  LOC_TEXT_SIGIL_DESC_ARCH_THAVAEL,
  LOC_TEXT_SIGIL_DESC_ARCH_AZRAEL,
  LOC_TEXT_SIGIL_DESC_ARCH_CAMAEL,
  LOC_TEXT_SIGIL_DESC_ARCH_JOPHIEL,

  LOC_TEXT_SIGIL_INTENT_COMMON_HEALTH,
  LOC_TEXT_SIGIL_INTENT_COMMON_STAMINA,
  LOC_TEXT_SIGIL_INTENT_COMMON_MANA,
  LOC_TEXT_SIGIL_INTENT_COMMON_HP_REGEN,
  LOC_TEXT_SIGIL_INTENT_COMMON_STAMINA_REGEN,
  LOC_TEXT_SIGIL_INTENT_COMMON_MANA_REGEN,
  LOC_TEXT_SIGIL_INTENT_COMMON_MOVE_SPEED,
  LOC_TEXT_SIGIL_INTENT_COMMON_AOE,
  LOC_TEXT_SIGIL_INTENT_COMMON_OVERALL_DAMAGE,
  LOC_TEXT_SIGIL_INTENT_COMMON_ABILITY_CD,
  LOC_TEXT_SIGIL_INTENT_COMMON_PROJECTILE_AMOUTH,
  LOC_TEXT_SIGIL_INTENT_COMMON_EXP_GAIN,
  LOC_TEXT_SIGIL_INTENT_COMMON_TOTAL_TRAIT_POINTS,
  LOC_TEXT_SIGIL_INTENT_COMMON_BASIC_ATTACK_DAMAGE,
  LOC_TEXT_SIGIL_INTENT_COMMON_BASIC_ATTACK_SPEED,
  LOC_TEXT_SIGIL_INTENT_COMMON_CRITICAL_CHANCE,
  LOC_TEXT_SIGIL_INTENT_COMMON_CRITICAL_DAMAGE,
  LOC_TEXT_SIGIL_INTENT_COMMON_OVERALL_LUCK,
  LOC_TEXT_SIGIL_INTENT_COMMON_DAMAGE_REDUCTION,
  LOC_TEXT_SIGIL_INTENT_COMMON_CONDITION_DURATION,
  LOC_TEXT_SIGIL_INTENT_COMMON_DAMAGE_OVER_TIME,
  LOC_TEXT_SIGIL_INTENT_COMMON_DAMAGE_DEFERRAL,
  LOC_TEXT_SIGIL_INTENT_COMMON_SIGIL_EFFECTIVENESS,
  LOC_TEXT_SIGIL_INTENT_COMMON_VITAL_SIGIL_EFFECTIVENESS,
  LOC_TEXT_SIGIL_INTENT_COMMON_LETHAL_SIGIL_EFFECTIVENESS,
  LOC_TEXT_SIGIL_INTENT_COMMON_DROP_RATE,
  LOC_TEXT_SIGIL_INTENT_COMMON_REWARD_MODIFIER,

  LOC_TEXT_WORLD_STAGE_WORK_IN_PROGRESS,
  LOC_TEXT_WORLD_STAGE_1_TITLE,

  LOC_TEXT_DISPLAY_ERROR_TEXT_STARTER_ABILITY_NOT_SELECTED,
  LOC_TEXT_DISPLAY_ERROR_TEXT_INSUFFICIENT_FUNDS,
  LOC_TEXT_DISPLAY_ERROR_TEXT_STAGE_IS_NOT_PLAYABLE,

  LOC_TEXT_MAX
} loc_text_id;

typedef struct loc_data {
  std::string language_name;
  std::string codepoints;
  std::array<std::string, LOC_TEXT_MAX> content;
  language_index index;
  loc_data(void) {
    this->language_name = std::string();
    this->codepoints = std::string();
    this->content.fill(std::string());
    this->index = LANGUAGE_INDEX_UNDEFINED;
  }
} loc_data;

typedef struct loc_content {
 const char* text;
}loc_content;

const char* lc_txt(i32 txt_id);

bool loc_parser_parse_localization_data_from_file(i32 pak_id, i32 file_index, language_index lang_index);
bool loc_parser_parse_localization_data(void);
bool loc_parser_parse_builtin_localization_data(void);

bool loc_parser_set_active_language_by_name(std::string language_name);
bool loc_parser_set_active_language_by_index(language_index _index);
bool loc_parser_set_active_language_builtin(void);

const std::array<loc_data, LANGUAGE_INDEX_MAX> * loc_parser_get_loc_langs(void);
loc_data* loc_parser_get_active_language(void);
const loc_data* loc_parser_get_language_by_index(language_index index);
const loc_data* loc_parser_get_language_by_name(const char * name);
language_index loc_parser_lang_name_to_index(const char * name);
const char * loc_parser_lang_index_to_name(language_index index);

#endif
